server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: math-modeling-agent
  
  # MySQL数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/math_agent?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # MyBatis配置
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.mathagent.model
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  
  # 数据库初始化配置
  sql:
    init:
      mode: ${DB_INIT_MODE:always}  # never, always, embedded
      schema-locations: classpath:sql/schema.sql
      continue-on-error: true
      separator: ";"
      encoding: UTF-8
  
  # Spring AI Alibaba配置
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY:your-api-key-here}
      chat:
        model: qwen-plus
      embedding:
        model: text-embedding-v3
      multimodal:
        model: qwen-vl-max

# 日志配置
logging:
  level:
    com.mathagent: DEBUG
    com.alibaba.cloud.ai: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
